package filesinterfaces

import (
	"context"
	"io"
	"time"

	"github.com/asciich/asciichgolangpublic/pkg/changesummary"
	"github.com/asciich/asciichgolangpublic/pkg/filesutils/filesoptions"
	"github.com/asciich/asciichgolangpublic/pkg/parameteroptions"
)

// A File represents any kind of file regardless if a local file or a remote file.
type File interface {
	AppendBytes(ctx context.Context, toWrite []byte) (err error)
	AppendString(ctx context.Context, toWrite string) (err error)
	Chmod(ctx context.Context, options *filesoptions.ChmodOptions) (err error)
	Chown(ctx context.Context, options *parameteroptions.ChownOptions) (err error)
	Create(ctx context.Context, options *filesoptions.CreateOptions) (err error)
	Delete(ctx context.Context, options *filesoptions.DeleteOptions) (err error)
	Exists(ctx context.Context) (exists bool, err error)
	GetAccessPermissions() (permission int, err error)
	GetAccessPermissionsString() (permissionString string, err error)
	GetBaseName() (baseName string, err error)
	GetDeepCopy() (deepCopy File)
	GetHostDescription() (hostDescription string, err error)
	GetLocalPath() (localPath string, err error)
	GetLocalPathOrEmptyStringIfUnset() (localPath string, err error)
	GetParentDirectory(ctx context.Context) (parentDirectory Directory, err error)
	GetPath() (path string, err error)
	GetSizeBytes(ctx context.Context) (fileSize int64, err error)
	GetUriAsString() (uri string, err error)
	MoveToPath(ctx context.Context, destPath string, useSudo bool) (movedFile File, err error)
	OpenAsReadCloser(ctx context.Context) (io.ReadCloser, error)
	OpenAsWriteCloser(ctx context.Context, options *filesoptions.WriteOptions) (io.WriteCloser, error)
	ReadAsBytes(ctx context.Context) (content []byte, err error)
	SecurelyDelete(ctx context.Context) (err error)
	String() (path string)
	Truncate(ctx context.Context, newSizeBytes int64) (err error)
	WriteBytes(ctx context.Context, toWrite []byte, options *filesoptions.WriteOptions) (err error)

	// All methods below this line can be implemented by embedding the `FileBase` struct:
	AppendLine(ctx context.Context, line string) (err error)
	CheckIsLocalFile(ctx context.Context) (err error)
	ContainsLine(ctx context.Context, line string) (containsLine bool, err error)
	CopyToFile(ctx context.Context, destFile File, options *filesoptions.CopyOptions) (err error)
	CreateParentDirectory(ctx context.Context) (err error)
	EnsureLineInFile(ctx context.Context, line string) (err error)
	EnsureEndsWithLineBreak(ctx context.Context) (err error)
	GetCreationDateByFileName(ctx context.Context) (creationDate *time.Time, err error)
	GetFileTypeDescription(ctx context.Context) (fileTypeDescription string, err error)
	GetMimeType(ctx context.Context) (mimeType string, err error)
	GetNumberOfLinesWithPrefix(ctx context.Context, prefix string, trimLines bool) (nLines int, err error)
	GetNumberOfNonEmptyLines(ctx context.Context) (nLines int, err error)
	GetParentDirectoryPath(ctx context.Context) (parentDirectoryPath string, err error)
	GetPathAndHostDescription() (path string, hostDescription string, err error)
	GetSha256Sum(context.Context) (sha256sum string, err error)
	GetTextBlocks(ctx context.Context) (textBlocks []string, err error)
	GetValueAsInt(ctx context.Context, key string) (value int, err error)
	GetValueAsString(ctx context.Context, key string) (value string, err error)
	IsContentEqualByComparingSha256Sum(ctx context.Context, other File) (isMatching bool, err error)
	IsEmptyFile(ctx context.Context) (isEmpty bool, err error)
	IsLocalFile(ctx context.Context) (isLocalFile bool, err error)
	IsMatchingSha256Sum(sha256sum string) (isMatching bool, err error)
	IsPgpEncrypted(ctx context.Context) (isPgpEncrypted bool, err error)
	IsYYYYmmdd_HHMMSSPrefix() (hasDatePrefix bool, err error)
	PrintContentOnStdout(ctx context.Context) (err error)
	ReadAsBool(ctx context.Context) (content bool, err error)
	ReadAsFloat64(ctx context.Context) (content float64, err error)
	ReadAsInt(ctx context.Context) (content int, err error)
	ReadAsInt64(ctx context.Context) (content int64, err error)
	ReadAsLines(ctx context.Context) (contentLines []string, err error)
	ReadAsLinesWithoutComments(ctx context.Context) (contentLines []string, err error)
	ReadAsString(ctx context.Context) (content string, err error)
	ReadAsTimeTime(ctx context.Context) (time *time.Time, err error)
	ReadFirstLine(ctx context.Context) (firstLine string, err error)
	ReadFirstNBytes(ctx context.Context, numberOfBytesToRead int) (firstBytes []byte, err error)
	ReadFirstLineAndTrimSpace(ctx context.Context) (firstLine string, err error)
	ReadLastCharAsString(ctx context.Context) (lastChar string, err error)
	RemoveLinesWithPrefix(ctx context.Context, prefix string) (err error)
	ReplaceLineAfterLine(ctx context.Context, lineToFind string, replaceLineAfterWith string) (changeSummary *changesummary.ChangeSummary, err error)
	SortBlocksInFile(ctx context.Context) (err error)
	TrimSpacesAtBeginningOfFile(ctx context.Context) (err error)
	WriteInt64(ctx context.Context, toWrite int64) (err error)
	WriteLines(ctx context.Context, linesToWrite []string) (err error)
	WriteString(ctx context.Context, content string, options *filesoptions.WriteOptions) (err error)
	WriteTextBlocks(ctx context.Context, textBlocks []string) (err error)
}
