package iscsigeneric

import (
	"context"
	"crypto/rand"
	"encoding/hex"

	"github.com/asciich/asciichgolangpublic/pkg/logging"
	"github.com/asciich/asciichgolangpublic/pkg/tracederrors"
)

// DefaultInitiatorNamePrefix is the IQN prefix used by open-iscsi (iscsi-iname) to generate initiator names.
const DefaultInitiatorNamePrefix = "iqn.2016-04.com.open-iscsi"

// initiatorNameRandomBytes is the number of random bytes used for the unique part of the initiator name.
// 6 bytes result in 12 hex characters which matches the format generated by open-iscsi.
const initiatorNameRandomBytes = 6

// GenerateInitiatorName generates a new random iSCSI initiator name in the open-iscsi format.
//
// Example: iqn.2016-04.com.open-iscsi:fe84975ad66d
//
// This function operates purely in memory and does not require root privileges.
// Every call returns a new random initiator name.
func GenerateInitiatorName(ctx context.Context) (string, error) {
	randomBytes := make([]byte, initiatorNameRandomBytes)

	_, err := rand.Read(randomBytes)
	if err != nil {
		return "", tracederrors.TracedErrorf("Failed to read random bytes to generate iSCSI initiator name: %w", err)
	}

	ret := DefaultInitiatorNamePrefix + ":" + hex.EncodeToString(randomBytes)

	logging.LogInfoByCtxf(ctx, "Generated iSCSI initiator name '%s'.", ret)

	return ret, nil
}
