package kubeletutils

import (
	"context"
	"fmt"
	"strings"

	"github.com/asciich/asciichgolangpublic/pkg/commandexecutor/commandexecutorexecoo"
	"github.com/asciich/asciichgolangpublic/pkg/commandexecutor/commandexecutorinterfaces"
	"github.com/asciich/asciichgolangpublic/pkg/filesutils/commandexecutorfile"
	"github.com/asciich/asciichgolangpublic/pkg/filesutils/filesoptions"
	"github.com/asciich/asciichgolangpublic/pkg/httputils/httpcommandexecutorclientoo"
	"github.com/asciich/asciichgolangpublic/pkg/httputils/httpoptions"
	"github.com/asciich/asciichgolangpublic/pkg/logging"
	"github.com/asciich/asciichgolangpublic/pkg/osutils/linuxutils/systemdutils"
	"github.com/asciich/asciichgolangpublic/pkg/tracederrors"
)

const (
	kubeletServicePath = "/etc/systemd/system/kubelet.service"
	kubeletDropInDir   = "/etc/systemd/system/kubelet.service.d"
	kubeletDropInPath  = "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
	kubeletServiceName = "kubelet"
	templateBaseUrl    = "https://raw.githubusercontent.com/kubernetes/release"
)

// prepareServiceOptions applies defaults to the given service options.
func prepareServiceOptions(options *InstallKubeletServiceOptions) *InstallKubeletServiceOptions {
	if options == nil {
		options = DefaultInstallKubeletServiceOptions()
	}
	if options.ReleaseVersion == "" {
		options.ReleaseVersion = "v0.16.2"
	}
	if options.BinPath == "" {
		options.BinPath = "/bin"
	}
	// UseSudo defaults to true if not set
	return options
}

// kubeadmDropInContent returns the standard kubeadm drop-in configuration for
// the kubelet systemd service. It is generated locally instead of being
// downloaded from the kubernetes/release templates so the content is pinned and
// does not depend on network access at install time.
//
// Note: "--bootstrap-kubeconfig" is REQUIRED. Without it a node created via
// "kubeadm join" cannot perform the kubelet TLS bootstrap: the kubelet would
// crash-loop because /etc/kubernetes/kubelet.conf does not exist yet, so it
// never runs the static pods (apiserver, etcd) needed to complete the join.
func kubeadmDropInContent(binPath string) string {
	return fmt.Sprintf(`# This drop-in is generated by kubeletutils and matches the upstream kubeadm
# kubelet drop-in. "--bootstrap-kubeconfig" is required for "kubeadm join" to
# perform the kubelet TLS bootstrap.
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically.
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for last-resort overrides of the kubelet args.
EnvironmentFile=-/etc/default/kubelet
ExecStart=
ExecStart=%s/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
`, binPath)
}

// InstallKubeletService installs the kubelet systemd unit and the kubeadm
// drop-in configuration on the local machine.
func InstallKubeletService(ctx context.Context, options *InstallKubeletServiceOptions) error {
	return InstallKubeletServiceUsingCommandExecutor(ctx, commandexecutorexecoo.Exec(), options)
}

// InstallKubeletServiceUsingCommandExecutor installs the kubelet systemd unit
// and the kubeadm drop-in configuration using the given command executor.
func InstallKubeletServiceUsingCommandExecutor(ctx context.Context, commandExecutor commandexecutorinterfaces.CommandExecutor, options *InstallKubeletServiceOptions) error {
	if commandExecutor == nil {
		return tracederrors.TracedErrorNil("commandExecutor")
	}

	options = prepareServiceOptions(options)

	logging.LogInfoByCtxf(ctx, "Install kubelet systemd service started.")

	serviceUrl := fmt.Sprintf(
		"%s/%s/cmd/krel/templates/latest/kubelet/kubelet.service",
		templateBaseUrl, options.ReleaseVersion,
	)

	client, err := httpcommandexecutorclientoo.NewClient(commandExecutor)
	if err != nil {
		return err
	}

	// Main service unit:
	// Fetch the template and rewrite the "/usr/bin" prefix to the configured
	// BinPath in Go.
	serviceContent, err := client.SendRequestAndGetBodyAsString(ctx, &httpoptions.RequestOptions{
		Url: serviceUrl,
	})
	if err != nil {
		return err
	}

	serviceContent = strings.ReplaceAll(serviceContent, "/usr/bin", options.BinPath)

	err = commandexecutorfile.WriteBytes(ctx, commandExecutor, kubeletServicePath, []byte(serviceContent), &filesoptions.WriteOptions{
		UseSudo: options.UseSudo,
	})
	if err != nil {
		return err
	}

	// Ensure the drop-in directory exists.
	err = commandexecutorfile.CreateDirectory(ctx, commandExecutor, kubeletDropInDir, &filesoptions.CreateOptions{
		UseSudo: options.UseSudo,
	})
	if err != nil {
		return err
	}

	// kubeadm drop-in:
	// Generated locally (Option B) instead of downloaded, to avoid the
	// unsupported "--bootstrap-kubeconfig" flag from the upstream template.
	dropInContent := kubeadmDropInContent(options.BinPath)

	err = commandexecutorfile.WriteBytes(ctx, commandExecutor, kubeletDropInPath, []byte(dropInContent), &filesoptions.WriteOptions{
		UseSudo: options.UseSudo,
	})
	if err != nil {
		return err
	}

	// Reload systemd so it picks up the new unit files.
	err = systemdutils.DaemonReload(ctx, commandExecutor)
	if err != nil {
		return err
	}

	logging.LogInfoByCtxf(ctx, "Install kubelet systemd service finished.")
	return nil
}
